[package]
name = "nu_plugin_redb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-plugin = { version = "0.89" }
nu-protocol = { version = "0.89", features = ["plugin"] }

redb = "1.5.0"
